name: Create Release

on:
  push:
    branches:
      - main_tmp

jobs:
  update-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Release Tag
        id: get_release_tag
        run: echo "Release Tag: ${{ github.event.head_commit.message }}"